CAMP-24
bitzquad/docs-bitzquad-academy pull request #21
Opened 2023-03-16 03:22 UTC by hariwij

- Add section about MongoDB Compass to the acedemy docs.

2023-03-16 03:26 UTC, kesaralive approved these changes

2023-03-20 13:16 UTC, IsuruVihan commented on docs/content/services/connect_mongodb_database_cluster.md
> +    -   Then you need to provide the connection details. You can find the connection details in the **Connect** tab of your database cluster. You can see the following screen. Copy the connection URI
- How can I **find** the connection details in the **Connect** tab?
- Where's the **Connection String Only** field?
- It's better to point out the UI elements in the images which will be used by the user.

2023-03-20 13:24 UTC, IsuruVihan commented on docs/content/services/connect_mongodb_database_cluster.md
> +    -   When the connection is established, you can see the following screen. You can see the databases in your database cluster in the left side of the screen. You can see the collections in the sel
- Present these information as an unordered list.
- Mark the relevant UI components in the image.

2023-03-20 13:26 UTC, IsuruVihan commented on docs/content/services/connect_mongodb_database_cluster.md
> +    -   There is a tab called **Databases** in the top middle of the screen. You can click on it to view the databases in your database cluster. In here you can see some information about the databas
- Do we need to mention about **Creating Database**?

2023-03-20 13:27 UTC, IsuruVihan commented on docs/content/services/connect_mongodb_database_cluster.md
> +     <kbd>![compass-collections.png](../../img/services/connect_mongodb_database_cluster/compass-collections.png)</kbd>
- Mark the relevant UI components in the image.

2023-03-20 13:27 UTC, IsuruVihan commented on docs/content/services/connect_mongodb_database_cluster.md
> +    <kbd>![compass-view-documents.png](../../img/services/connect_mongodb_database_cluster/compass-view-documents.png)</kbd>
- Mark the relevant UI components in the image.

2023-03-20 13:30 UTC, IsuruVihan requested changes
Do the changes that I've requested. After that I'll go through typo and comment on that as well.👌

2023-03-28 22:56 UTC, IsuruVihan commented on docs/content/services/connect_mongodb_database_cluster.md
> +    -   When the connection is established, you can see the following screen. You can see the databases in your database cluster in the left side of the screen. You can see the collections in the sel
I can't see the list

2023-03-29 02:11 UTC, hariwij commented on docs/content/services/connect_mongodb_database_cluster.md
> +    -   When the connection is established, you can see the following screen. You can see the databases in your database cluster in the left side of the screen. You can see the collections in the sel
![image](https://user-images.githubusercontent.com/53245949/228408270-5b42f7ee-498c-407f-b1d5-f6c790a315c4.png)
Check this out. Changes are already done.

2023-04-04 14:40 UTC, IsuruVihan approved these changes
Looks good to me. Don't forget to check grammar twice before merging @hariwij

2023-04-05 09:06 UTC, merged